DE/AutonomousVehicles.rdf
EC/AutoSchemaOrg.rdf
EC/VehicleSales.rdf
EC/VolkswagenVehicles.rdf
VS/VehicleSignals.rdf

date, dateTime and other problems with ranges cleaned up

---

DE/AutonomousVehicles.rdf

FullDrivingAutomation depends on human drivers

---

DE/AutonomousVehicles.rdf

Changes after the last AV WG meeting.

---

DE/AutonomousVehicles.rdf
DE/TrafficCrashes.rdf
MO/MiddleOntology.rdf

cleaning up

---

DE/AutonomousVehicles.rdf

"master/latest/" removed

---

DE/AutonomousVehicles.rdf
DE/CarControl.rdf
DE/TrafficEnvironment.rdf

reorganization

---

MO/MiddleOntology.rdf
VC/MetadataVC.rdf

consistency

---

MO/MiddleOntology.rdf
VC/VehicleParts.rdf
VS/MetadataVS.rdf
VS/VehicleSignals.rdf

consistent naming convention + removing transitivity

---

DE/AutonomousVehicles.rdf
DE/CarControl.rdf
DE/TrafficEnvironment.rdf
DE/TrafficIncidents.rdf
MO/MiddleOntology.rdf
VC/VehicleCore.rdf
VC/VehicleParts.rdf
catalog-v001.xml

towards BFO

---

AboutAUTOProd.rdf

Prod file added

---

etc/vocabulary/README.md
etc/vocabulary/classes.sparql
etc/vocabulary/properties.sparql
etc/vocabulary/scaffolding.ttl
etc/vocabulary/subclasses.sparql
etc/vocabulary/subproperties.sparql

Fixes:https://github.com/edmcouncil/auto/issues/61

SPARQL queries for vocabulary creation added

---

AV/VehicleAutomationLevels.rdf
AV/catalog-v001.xml
AboutAUTODev.rdf
catalog-v001.xml

Vehicle Automation Levels Seed Ontology

---

VC/VehicleCore.rdf

Labels fixed in VC ontology

---

VC/VehicleParts.rdf

Labels are fixed in VP ontology

---

DE/TrafficIncidents.rdf

Labels are fixed in TI ontology

---

DE/CarControl.rdf

Labels are fixed in CC ontology

---

DE/TrafficEnvironment.rdf

Labels are fixed in TE ontology

---

AV/VehicleAutomationLevels.rdf

Signed-off-by: unknown <mar.skul@gmail.com>
Fixes: #68

Update of AV ontology

---

etc/onto-viewer-web-app/config/application_config.yaml

Signed-off-by: Patrycja Miazek <patrycja.miazek@makolab.com>

Add new configuration 

---

DE/CarControl.rdf
DE/TrafficEnvironment.rdf
DE/TrafficIncidents.rdf

Finishing work for labels in all domains

---

DE/CarControl.rdf
DE/TrafficEnvironment.rdf
DE/TrafficIncidents.rdf
VC/VehicleCore.rdf
VC/VehicleParts.rdf

Missing definitions added

---

AV/VehicleAutomationLevels.rdf

Signed-off-by: Marcin Skulimowski <mar.skulim@gmail.com>

OperatingCondition class and subclasses of ODD added

---

DE/CarControl.rdf
DE/TrafficEnvironment.rdf
DE/TrafficIncidents.rdf
VC/VehicleCore.rdf
VC/VehicleParts.rdf

This add new classes for vehicles from Code of Federal Regulations of USA and from Uniform Vehicle Code.

New classes for vehicles added

---

etc/onto-viewer-web-app/config/ontology_config.yaml

Signed-off-by: Patrycja Miazek <patrycjamiazek17@gmail.com>

Update config file

---

VC/VehicleParts.rdf

Logical descriptions for new classes added

---

AV/VehicleAutomationLevels.rdf

Modified classes: HumanUser and MotorVehicle. Roles of a human user added to driving automation levels.
Signed-off-by: Marcin Skulimowski <mar.skulim@gmail.com>

Modified classes: HumanUser, MotorVehicle

---

AV/VehicleAutomationLevels.rdf
AV/catalog-v001.xml
MetadataAUTO.rdf

Minor fixes to pull-requests 92 and 94

---

AV/VehicleAutomationLevels.rdf

1) new classes added 
2) revised definitions, explanatory notes or examples for several classes
Signed-off-by: mskulim <mar.skulim@gmail.com>

Toward compliance with SAE-J3016 APR2021

---

AV/VehicleAutomationLevels_2021.rdf

Signed-off-by: mskulim <mar.skulim@gmail.com>

SAE-J3016 - revision 2021 - logical descriptions for classes

---

AV/VehicleAutomationLevels_2018.rdf
AV/VehicleAutomationLevels_2021.rdf
AV/catalog-v001.xml
AboutAUTODev.rdf
AboutAUTOProd.rdf
catalog-v001.xml

Update metadata for VehicleAutomationLevels ontology

---

AV/2018/VehicleAutomationLevels_2018.rdf
AV/VehicleAutomationLevels.rdf
AboutAUTODev.rdf
catalog-v001.xml

Hotfix to AV metadata

---

AV/VehicleAutomationLevels.rdf

1) Logical descriptions for selected classes added or modified (especially new classes from SAE-J3016, revision 2021-04).
2) The value constraint owl:allValuesFrom added. 
3) Several properties added or modified. 
4) Several names corrected.
Signed-off-by: Marcin Skulimowski <mar.skulim@gmail.com>

Logical descriptions for several classes added or modified

---

AV/MetadataAV.rdf
etc/onto-viewer-web-app/config/groups_config.yaml

Update of metadata and config

---

AV/MetadataAV.rdf
AV/VehicleAutomationLevels.rdf

This updates the list of VAL ontology creators.

Update of VAL ontology creators

---

VS/VehicleSignals.rdf
VS/catalog-v001.xml

Add label to Camera class in VS ontology

---

VS/VehicleSignals.rdf

Signed-off-by: kwlodarczyk0 <wlodarczyk.krystian00@gmail.com>
Fixes: #118

Add missing labels in VS ontology

---

VS/VehicleSignals.rdf
VS/catalog-v001.xml

Signed-off-by: Bardawulf <kanarek365@gmail.com>
Fixes: #126

added labels to multiple resources in VS ontology

---

VC/VehicleCore.rdf
VC/catalog-v001.xml

Signed-off-by: jakobek09 <86194028+jakobek09@users.noreply.github.com>
Fixes: #132

Change some labels to synonyms in VehicleCore ontology

---

etc/onto-viewer-web-app/config/integration_config.yaml

This adds a new config file for onto-viewer.

integration.yaml added

---

etc/onto-viewer-web-app/config/groups_config.yaml
etc/onto-viewer-web-app/config/label_config.yaml

update config files
